# Generated by Django 3.2.9 on 2022-01-09 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribers',
            new_name='NewsletterUser',
        ),
        migrations.RenameField(
            model_name='newsletteruser',
            old_name='date',
            new_name='date_added',
        ),
    ]
