# Generated by Django 3.2.9 on 2022-01-09 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20220109_1905'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsletterUser',
            new_name='Subscriber',
        ),
        migrations.RenameField(
            model_name='subscriber',
            old_name='date_added',
            new_name='date',
        ),
    ]
